INSERT INTO pronostico_deportivo.Partido
VALUES	(10,'Platense','Estudiantes LP',1,2),
		(11,'Sarmiento','Godoy Cruz',1,1),
		(12,'Tigre','Huracán',1,0),
		(13,'Argentinos Jrs','Gimnasia LP',2,4),
		(14,'Racing','Atl Tucumán',1,3),
		(15,'Barracas Central','Defensa y Justicia',0,2),
		(16,'River Plate','Independiente',2,0),
		(17,'Estudiante LP','Talleres',1,0),
		(18,'Instituto','Banfield',1,1),
		(19,'Rosario Central','Boca Jrs',0,2);

INSERT INTO pronostico_deportivo.Pronostico
VALUES	(10,'Platense','GANADOR','Julieta','2'),
		(11,'Sarmiento','EMPATE','Julieta','2'),
		(12,'Tigre','PERDEDOR','Julieta','2'),
		(13,'Argentinos Jrs','GANADOR','Julieta','2'),
		(14,'Racing','PERDEDOR','Julieta','2'),
		(15,'Barracas Central','GANADOR','Julieta','2'),
		(16,'River Plate','PERDEDOR','Julieta','2'),
		(17,'Estudiante LP','GANADOR','Julieta','2'),
		(18,'Instituto','EMPATE','Julieta','2'),
		(19,'Rosario Central','EMPATE','Julieta','2'),
		(10,'Platense','PERDEDOR','Rodrigo','2'),
		(11,'Sarmiento','EMPATE','Rodrigo','2'),
		(12,'Tigre','EMPATE','Rodrigo','2'),
		(13,'Argentinos Jrs','PERDEDOR','Rodrigo','2'),
		(14,'Racing','GANADOR','Rodrigo','2'),
		(15,'Barracas Central','GANADOR','Rodrigo','2'),
		(16,'River Plate','PERDEDOR','Rodrigo','2'),
		(17,'Estudiante LP','GANADOR','Rodrigo','2'),
		(18,'Instituto','EMPATE','Rodrigo','2'),
		(19,'Rosario Central','PERDEDOR','Rodrigo','2');